name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-server:
    runs-on: ubuntu-latest
    name: Build
    steps:

      - uses: actions/checkout@v2

      - name: Build binary
        uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: golang:latest
          options: -v ${{ github.workspace }}:/src -w /src
          run: make

      - name: Log in to the GitHub container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/kastelo/go-import-redirector:latest
